name: "Setup AWS CLI"
author: "Sumanshu Nankana"
description: "Setup AWS CLI to use in github actions"
inputs:
  region:
    description: "AWS Region"
    required: true
  access-key-id:
    description: "AWS Access Key ID"
    required: true
  secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-cli-version:
    description: "AWS CLI Version to Install"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup and Configure AWS CLI
      run: |
        python -m venv .venv
        source .venv/bin/activate
        # if aws-cli-version is empty string then install latest
        if [ -z "${{ inputs.aws-cli-version }}" ]; then
          pip install awscli
        else
          pip install awscli==${{ inputs.aws-cli-version }}
        aws configure set default.region ${{ inputs.region }}
        aws configure set aws_access_key_id ${{ inputs.access-key-id }}
        aws configure set aws_secret_access_key ${{ inputs.secret-access-key }}
      shell: bash
    - name: Check AWS CLI Version
      run:  aws --version
      shell: bash

