name: 2. Variables
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  - workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Variable
        run: echo ${{ vars.WELCOME }}

      - name: Setup and Print Environment Variables
        env:
          HOST: 'localhost'
          PORT: '8080'
        run: echo "Running on ${{ env.HOST }} and ${{ env.PORT }}"

