name: 8 Startegy Matrix
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  workflow_dispatch

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9, 3.10.13, 3.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Override Python Version in pyproject.toml
        run: sed -i 's/^python = ".*"$/python = "^${{ matrix.python_version }}"/' pyproject.toml

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry lock
          poetry install --with dev --no-root

      - name: Run tests and generate HTML report
        continue-on-error: true
        run: poetry run pytest --html=result.html

      - name: Upload HTML result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: result.html
          retention-days: 1