name: 9. Reusable Workflow
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  workflow_dispatch

jobs:
  build_and_test:
      uses: ./.github/workflows/Common_Workflow.yaml
      with:
        job: unit-test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Deployment Step
        run: echo "Doing the Deployment"

