name: Common Workflow aka Reusable Workflow
on:
  workflow_call

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --no-root

      - name: Run tests and generate HTML report
        continue-on-error: true
        run: poetry run pytest --html=result.html

      - name: Upload HTML result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: result.html
          retention-days: 1

  second-job:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      run: echo "Unit Test Is Completed"